### ISSUE TITLE
configuration file 'gpflowrc' missing from package directory

### ISSUE THREAD

**Issue by jereliu** [ssydasheng/GPflow-Slim#1]
System: Ubuntu 16.04 LTS
Python version: anaconda3, Python 3.6.4.

When installing the package using the command `python setup.py install`, the configuration file `gpflowrc` was not copied to the pip installation directory (in my case it is something like ~/anaconda3/lib/python3.6/site-packages/gpflowSlim-1.0.0-py3.6.egg/). 

Consequently, any call to basic configurations such as `gpf.settings.tf_float` will raise error, rendering the functions under `gpf.kernels` not usable.

User can fix this issue easily by copying the 'gpflowrc' file to installation directory, however having setup.py to do this automatically at installation stage would be nice.

**Comment by ssydasheng** [comment]
Good catch! It seems to be problematic for ` python setup.py install `, can you try using ` python setup.py develop ` ? I bet it should work well.

**Comment by jereliu** [comment]
Hey @ssydasheng !  yep `python setup.py develop` works nicely! Thanks!

In that case it probably would be a good idea to mention this in README.md. I bet less adventurous users will try `python setup.py install` first for sure...

Anyways, the issue is resolved.

**Comment by ssydasheng** [comment]
You are absolutely right. Thanks, I will correct that.
