### ISSUE TITLE
Parameter transform

### ISSUE THREAD

**Issue by DimitrisCC** [ssydasheng/GPflow-Slim#4]
https://github.com/ssydasheng/GPflow-Slim/blob/96ea01e5aa7b488997755a2b35bc433ca8a85b39/gpflowSlim/params.py#L142

Why is the stored parameter value transformed through the backwards function of the transformation?
Shouldn't it stay as it is and be transformed forwards when necessary?

**Comment by ssydasheng** [comment]
cuz the param value is the constrained input value. For example, if we initialize a positive variable 1, then we first backward to get the unconstrained value and inutialize it. So it corresponds to initialize the constrained input value as 1.

**Comment by DimitrisCC** [comment]
Thanks for the clarification. Is it done the same way in the Param class of gpflow? I don't see any backwarding in that.

**Comment by ssydasheng** [comment]
They do have it. 

In GPflow-v1.5, https://github.com/GPflow/GPflow/blob/03af631bdbefbe67f85c81e74df10b860d05588f/gpflow/params/parameter.py#L375

If you track the **self._initial_value_tensor**, you will find that they do feed this placeholder with the backward value in L189.

GPflow-Slim is purely based on the GPflow-1. So their core structures are the same.

**Comment by DimitrisCC** [comment]
Great! Thanks for the clarification!
